### ISSUE TITLE
Need help in opening the .pth file

### ISSUE THREAD

**Issue by RaswanthGitHub** [safi842/Microstructure-GAN#1]
How to open .pth file

**Comment by safi842** [comment]
https://github.com/safi842/Microstructure-GAN/blob/73c0d7ec68b54f6ef1aee5db6710539879ebd837/app/gan_app.py#L75-L78

Code for the generator is provided in [biggan.py](https://github.com/safi842/Microstructure-GAN/blob/main/app/biggan.py)

**Comment by RaswanthGitHub** [comment]
Thank you so much for your reply.
Can you also please share me the "new metadata.xlsx". 
I have downloaded 1700+ UHCSDB images. 
Only the Excel file is missing.

**Comment by safi842** [comment]
I have uploaded the excel file. The numbering of the micrographs in UHCSDB is misleading. There are only 961 micrographs. Out of which only 598 have all the processing parameters. The file  `new_metadata.xlsx` contains information only on the aforementioned 598 images. If you need the entire list you can find it here : [uhcs-metadata.csv](https://github.com/bdecost/uhcsdb/blob/master/data/uhcs-metadata.csv)
